CREATE VIEW VIEW_USER_INFORMATION AS 
	SELECT U.USER_ID,U.FIRST_NAME,U.LAST_NAME,U.YEAR_OF_BIRTH,U.MONTH_OF_BIRTH,U.DAY_OF_BIRTH,U.GENDER,
	C1.CITY_NAME AS CURRENT_CITY,C1.STATE_NAME AS CURRENT_STATE,C1.COUNTRY_NAME AS CURRENT_COUNTRY,C2.CITY_NAME AS HOMETOWN_CITY,C2.STATE_NAME AS HOMETOWN_STATE,C2.COUNTRY_NAME AS HOMETOWN_COUNTRY,
	P.INSTITUTION AS INSTITUTION_NAME,E.PROGRAM_YEAR,P.CONCENTRATION AS PROGRAM_CONCENTRATION,P.DEGREE AS PROGRAM_DEGREE
	FROM USERS U 
	INNER JOIN USER_CURRENT_CITY UC ON UC.USER_ID=U.USER_ID
	INNER JOIN CITIES C1 ON UC.CURRENT_CITY_ID=C1.CITY_ID
	INNER JOIN USER_HOMETOWN_CITY UH ON U.USER_ID=UH.USER_ID
	INNER JOIN CITIES C2  ON UH.HOMETOWN_CITY_ID=C2.CITY_ID
	INNER JOIN EDUCATION E ON E.USER_ID=U.USER_ID 
	INNER JOIN PROGRAMS P ON P.PROGRAM_ID=E.PROGRAM_ID;



CREATE VIEW VIEW_ARE_FRIENDS AS
	SELECT USER1_ID,USER2_ID FROM FRIENDS;


CREATE VIEW VIEW_PHOTO_INFORMATION AS
	SELECT A.ALBUM_ID,A.ALBUM_OWNER_ID,A.COVER_PHOTO_ID,A.ALBUM_NAME,A.ALBUM_CREATED_TIME,
	A.ALBUM_MODIFIED_TIME,A.ALBUM_LINK,A.ALBUM_VISIBILITY,P.PHOTO_ID,P.PHOTO_CAPTION,P.PHOTO_CREATED_TIME,
	P.PHOTO_MODIFIED_TIME,P.PHOTO_LINK
	FROM ALBUMS A
	INNER JOIN PHOTOS P ON P.ALBUM_ID=A.ALBUM_ID;

CREATE VIEW VIEW_TAG_INFORMATION AS
	SELECT T.TAG_PHOTO_ID,T.TAG_SUBJECT_ID,T.TAG_CREATED_TIME,T.TAG_X,T.TAG_Y
	FROM TAGS T;

CREATE VIEW VIEW_EVENT_INFORMATION AS
	SELECT U.EVENT_ID,U.EVENT_CREATOR_ID,U.EVENT_NAME,U.EVENT_TAGLINE,U.EVENT_DESCRIPTION,U.EVENT_HOST,
	U.EVENT_TYPE,U.EVENT_SUBTYPE,U.EVENT_LOCATION,C.CITY_NAME,C.STATE_NAME,C.COUNTRY_NAME,
	U.EVENT_START_TIME,U.EVENT_END_TIME
	FROM USER_EVENTS U
	INNER JOIN CITIES C ON C.CITY_ID=U.EVENT_CITY_ID;

